DROP TABLE IF EXISTS AGENTS CASCADE;

CREATE TABLE AGENTS (
		AGENT_CODE CHARACTER VARYING(6) NOT NULL PRIMARY KEY,
		AGENTE_NAME CHARACTER VARYING(40),
		WORKING_AREA CHARACTER VARYING(35),
		COMMISSION NUMERIC(10,2),
		PHONE_NO CHARACTER VARYING(15),
		COUNTRY  CHARACTER VARYING(25)
);

DROP TABLE IF EXISTS CUSTOMER CASCADE;

CREATE TABLE CUSTOMER (
	CUST_CODE CHARACTER VARYING(6) NOT NULL PRIMARY KEY,
	CUST_NAME CHARACTER VARYING(40) NOT NULL,
	CUST_CITY CHARACTER VARYING(35),
	WORKING_AREA CHARACTER VARYING(35) NOT NULL,
	CUST_COUNTRY CHARACTER VARYING(20) NOT NULL,
	GRADE NUMERIC,
	OPENING_AMT NUMERIC(12,2) NOT NULL,
	RECEIVE_AMT NUMERIC(12,2) NOT NULL,
	PAYMENT_AMT NUMERIC(12,2) NOT NULL,
	OUTSTANDING_AMT NUMERIC(12,2) NOT NULL,
	PHONE_NO CHARACTER VARYING(17) NOT NULL,
	AGENT_CODE CHARACTER VARYING(6) NOT NULL REFERENCES AGENTS
);

DROP TABLE IF EXISTS ORDERS CASCADE;

CREATE TABLE ORDERS (
	ORD_NUM NUMERIC(6,0) NOT NULL PRIMARY KEY,
	ORD_AMOUNT NUMERIC(12,2) NOT NULL,
	ADVANCE_AMOUNT NUMERIC(12,2) NOT NULL,
	ORD_DATE DATE NOT NULL,
	CUST_CODE CHARACTER VARYING(6) NOT NULL REFERENCES CUSTOMER,
	AGENT_CODE CHARACTER VARYING(6) NOT NULL REFERENCES AGENTS,
	ORD_DESCRIPTION CHARACTER VARYING(60) NOT NULL
);